In [132]:
# Import the requests library.
import requests
import pandas as pd
from bs4 import BeautifulSoup
import requests
import time
import numpy as np

In [10]:
covid_data = pd.read_csv('counties.csv')
covid_df = pd.DataFrame(covid_data)
covid_df.head()

,fips,country,state,county,level,lat,locationId,long,population,metrics.testPositivityRatio,...,actuals.vaccinesDistributed,actuals.vaccinationsInitiated,actuals.vaccinationsCompleted,lastUpdatedDate,url,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,cdcTransmissionLevel
0,2013,US,AK,Aleutians East Borough,county,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,3337,NaN,...,NaN,2512.0,2313.0,2021-11-04,https://covidactnow.org/us/alaska-ak/county/al...,0.753,0.693,0.0,NaN,2
1,2016,US,AK,Aleutians West Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02016,NaN,5634,0.000,...,NaN,3738.0,3152.0,2021-11-04,https://covidactnow.org/us/alaska-ak/county/al...,0.663,0.559,0.0,NaN,1
2,2020,US,AK,Anchorage Municipality,county,NaN,iso1:us#iso2:us-ak#fips:02020,NaN,288000,0.083,...,NaN,185037.0,162085.0,2021-11-04,https://covidactnow.org/us/alaska-ak/county/an...,0.642,0.563,5.0,NaN,3
3,2050,US,AK,Bethel Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02050,NaN,18386,0.006,...,NaN,11597.0,10675.0,2021-11-04,https://covidactnow.org/us/alaska-ak/county/be...,0.631,0.581,0.0,NaN,3
4,2060,US,AK,Bristol Bay Borough,county,NaN,iso1:us#iso2:us-ak#fips:02060,NaN,836,NaN,...,NaN,NaN,NaN,2021-11-04,https://covidactnow.org/us/alaska-ak/county/br...,NaN,NaN,0.0,NaN,0

In [11]:
column_list = []
for column in covid_df.columns:
    column_list.append(column)
column_list

['fips',
 'country',
 'state',
 'county',
 'level',
 'lat',
 'locationId',
 'long',
 'population',
 'metrics.testPositivityRatio',
 'metrics.testPositivityRatioDetails.source',
 'metrics.caseDensity',
 'metrics.contactTracerCapacityRatio',
 'metrics.infectionRate',
 'metrics.infectionRateCI90',
 'unused1',
 'unused2',
 'metrics.icuCapacityRatio',
 'riskLevels.overall',
 'riskLevels.testPositivityRatio',
 'riskLevels.caseDensity',
 'riskLevels.contactTracerCapacityRatio',
 'riskLevels.infectionRate',
 'unused3',
 'riskLevels.icuCapacityRatio',
 'actuals.cases',
 'actuals.deaths',
 'actuals.positiveTests',
 'actuals.negativeTests',
 'actuals.contactTracers',
 'actuals.hospitalBeds.capacity',
 'actuals.hospitalBeds.currentUsageTotal',
 'actuals.hospitalBeds.currentUsageCovid',
 'unused4',
 'actuals.icuBeds.capacity',
 'actuals.icuBeds.currentUsageTotal',
 'actuals.icuBeds.currentUsageCovid',
 'unused5',
 'actuals.newCases',
 'actuals.vaccinesDistributed',
 'actuals.vaccinationsInitiated',
 'actuals.vaccinationsCompleted',
 'lastUpdatedDate',
 'url',
 'metrics.vaccinationsInitiatedRatio',
 'metrics.vaccinationsCompletedRatio',
 'actuals.newDeaths',
 'actuals.vaccinesAdministered',
 'cdcTransmissionLevel']

In [12]:
drop_list = ['level','lat','locationId','long','unused1','unused2','unused3','unused4','unused5','url']

In [13]:
covid_df.drop(drop_list, axis=1, inplace=True)
covid_df.head()

,fips,country,state,county,population,metrics.testPositivityRatio,metrics.testPositivityRatioDetails.source,metrics.caseDensity,metrics.contactTracerCapacityRatio,metrics.infectionRate,...,actuals.newCases,actuals.vaccinesDistributed,actuals.vaccinationsInitiated,actuals.vaccinationsCompleted,lastUpdatedDate,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,cdcTransmissionLevel
0,2013,US,AK,Aleutians East Borough,3337,NaN,other,12.8,NaN,1.00,...,0,NaN,2512.0,2313.0,2021-11-04,0.753,0.693,0.0,NaN,2
1,2016,US,AK,Aleutians West Census Area,5634,0.000,other,5.1,NaN,1.00,...,2,NaN,3738.0,3152.0,2021-11-04,0.663,0.559,0.0,NaN,1
2,2020,US,AK,Anchorage Municipality,288000,0.083,other,79.2,NaN,0.88,...,172,NaN,185037.0,162085.0,2021-11-04,0.642,0.563,5.0,NaN,3
3,2050,US,AK,Bethel Census Area,18386,0.006,other,106.4,NaN,0.83,...,1,NaN,11597.0,10675.0,2021-11-04,0.631,0.581,0.0,NaN,3
4,2060,US,AK,Bristol Bay Borough,836,NaN,other,0.0,NaN,1.00,...,0,NaN,NaN,NaN,2021-11-04,NaN,NaN,0.0,NaN,0

In [14]:
for x in covid_df.columns:
    print(f'{x}: {covid_df[x].nunique()}')

fips: 3222
country: 1
state: 53
county: 1957
population: 3166
metrics.testPositivityRatio: 338
metrics.testPositivityRatioDetails.source: 1
metrics.caseDensity: 816
metrics.contactTracerCapacityRatio: 1
metrics.infectionRate: 92
metrics.infectionRateCI90: 118
metrics.icuCapacityRatio: 103
riskLevels.overall: 5
riskLevels.testPositivityRatio: 5
riskLevels.caseDensity: 5
riskLevels.contactTracerCapacityRatio: 2
riskLevels.infectionRate: 5
riskLevels.icuCapacityRatio: 5
actuals.cases: 2887
actuals.deaths: 654
actuals.positiveTests: 1
actuals.negativeTests: 1
actuals.contactTracers: 1
actuals.hospitalBeds.capacity: 637
actuals.hospitalBeds.currentUsageTotal: 563
actuals.hospitalBeds.currentUsageCovid: 171
actuals.icuBeds.capacity: 245
actuals.icuBeds.currentUsageTotal: 211
actuals.icuBeds.currentUsageCovid: 80
actuals.newCases: 234
actuals.vaccinesDistributed: 2
actuals.vaccinationsInitiated: 3081
actuals.vaccinationsCompleted: 3076
lastUpdatedDate: 1
metrics.vaccinationsInitiatedRatio: 584
metrics.vaccinationsCompletedRatio: 547
actuals.newDeaths: 17
actuals.vaccinesAdministered: 1256
cdcTransmissionLevel: 4

In [15]:
covid_df

,fips,country,state,county,population,metrics.testPositivityRatio,metrics.testPositivityRatioDetails.source,metrics.caseDensity,metrics.contactTracerCapacityRatio,metrics.infectionRate,...,actuals.newCases,actuals.vaccinesDistributed,actuals.vaccinationsInitiated,actuals.vaccinationsCompleted,lastUpdatedDate,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,cdcTransmissionLevel
0,2013,US,AK,Aleutians East Borough,3337,NaN,other,12.8,NaN,1.00,...,0,NaN,2512.0,2313.0,2021-11-04,0.753,0.693,0.0,NaN,2
1,2016,US,AK,Aleutians West Census Area,5634,0.000,other,5.1,NaN,1.00,...,2,NaN,3738.0,3152.0,2021-11-04,0.663,0.559,0.0,NaN,1
2,2020,US,AK,Anchorage Municipality,288000,0.083,other,79.2,NaN,0.88,...,172,NaN,185037.0,162085.0,2021-11-04,0.642,0.563,5.0,NaN,3
3,2050,US,AK,Bethel Census Area,18386,0.006,other,106.4,NaN,0.83,...,1,NaN,11597.0,10675.0,2021-11-04,0.631,0.581,0.0,NaN,3
4,2060,US,AK,Bristol Bay Borough,836,NaN,other,0.0,NaN,1.00,...,0,NaN,NaN,NaN,2021-11-04,NaN,NaN,0.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,56037,US,WY,Sweetwater County,42343,0.132,other,50.9,NaN,0.98,...,15,NaN,20879.0,16940.0,2021-11-04,0.493,0.370,11.0,NaN,3
3218,56039,US,WY,Teton County,23464,0.060,other,34.7,NaN,0.86,...,3,NaN,21728.0,19110.0,2021-11-04,0.926,0.770,0.0,NaN,3
3219,56041,US,WY,Uinta County,20226,0.119,other,33.9,NaN,0.79,...,10,NaN,9931.0,8552.0,2021-11-04,0.491,0.390,1.0,NaN,3
3220,56043,US,WY,Washakie County,7805,0.048,other,102.5,NaN,0.71,...,11,NaN,3208.0,2898.0,2021-11-04,0.411,0.370,0.0,NaN,3
3221,56045,US,WY,Weston County,6927,0.316,other,162.9,NaN,0.98,...,5,NaN,2475.0,2233.0,2021-11-04,0.357,0.320,0.0,NaN,3

In [16]:
covid_df.isnull().sum()

fips                                            0
country                                         0
state                                           0
county                                          0
population                                      0
metrics.testPositivityRatio                   247
metrics.testPositivityRatioDetails.source       0
metrics.caseDensity                             0
metrics.contactTracerCapacityRatio           3221
metrics.infectionRate                         260
metrics.infectionRateCI90                     260
metrics.icuCapacityRatio                     1781
riskLevels.overall                              0
riskLevels.testPositivityRatio                  0
riskLevels.caseDensity                          0
riskLevels.contactTracerCapacityRatio           0
riskLevels.infectionRate                        0
riskLevels.icuCapacityRatio                     0
actuals.cases                                   0
actuals.deaths                                171
actuals.positiveTests                        3221
actuals.negativeTests                        3221
actuals.contactTracers                       3221
actuals.hospitalBeds.capacity                 776
actuals.hospitalBeds.currentUsageTotal        783
actuals.hospitalBeds.currentUsageCovid        833
actuals.icuBeds.capacity                     1511
actuals.icuBeds.currentUsageTotal            1591
actuals.icuBeds.currentUsageCovid            1675
actuals.newCases                                0
actuals.vaccinesDistributed                  3188
actuals.vaccinationsInitiated                  11
actuals.vaccinationsCompleted                  11
lastUpdatedDate                                 0
metrics.vaccinationsInitiatedRatio             12
metrics.vaccinationsCompletedRatio             12
actuals.newDeaths                             171
actuals.vaccinesAdministered                 1922
cdcTransmissionLevel                            0
dtype: int64

In [17]:
len(covid_df.index)

3222

In [18]:
covid_df['actuals.positiveTests']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
3217   NaN
3218   NaN
3219   NaN
3220   NaN
3221   NaN
Name: actuals.positiveTests, Length: 3222, dtype: float64

In [19]:
or_df = covid_df[covid_df['state'] == 'OR']
or_df['actuals.hospitalBeds.currentUsageCovid']

2210      1.0
2211     11.0
2212     35.0
2213      2.0
2214      NaN
2215      3.0
2216      0.0
2217      1.0
2218     71.0
2219      9.0
2220      NaN
2221      1.0
2222      2.0
2223      3.0
2224     41.0
2225      0.0
2226     21.0
2227     23.0
2228      1.0
2229     48.0
2230      2.0
2231      6.0
2232      3.0
2233     48.0
2234      NaN
2235    123.0
2236      NaN
2237      NaN
2238      2.0
2239     11.0
2240      0.0
2241      1.0
2242      6.0
2243     64.0
2244      NaN
2245      7.0
Name: actuals.hospitalBeds.currentUsageCovid, dtype: float64

In [20]:
or_df

,fips,country,state,county,population,metrics.testPositivityRatio,metrics.testPositivityRatioDetails.source,metrics.caseDensity,metrics.contactTracerCapacityRatio,metrics.infectionRate,...,actuals.newCases,actuals.vaccinesDistributed,actuals.vaccinationsInitiated,actuals.vaccinationsCompleted,lastUpdatedDate,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,cdcTransmissionLevel
2210,41001,US,OR,Baker County,16124,0.082,other,22.1,NaN,0.67,...,4,NaN,13198.0,10724.0,2021-11-04,0.819,0.665,0.0,14464.0,3
2211,41003,US,OR,Benton County,93053,0.032,other,20.6,NaN,0.89,...,8,NaN,67443.0,63921.0,2021-11-04,0.725,0.687,0.0,136447.0,3
2212,41005,US,OR,Clackamas County,418187,0.066,other,22.1,NaN,1.02,...,97,NaN,274547.0,259633.0,2021-11-04,0.657,0.621,1.0,556214.0,3
2213,41007,US,OR,Clatsop County,40224,0.047,other,10.7,NaN,0.68,...,3,NaN,26694.0,24302.0,2021-11-04,0.664,0.604,0.0,49161.0,2
2214,41009,US,OR,Columbia County,52354,0.093,other,24.0,NaN,0.89,...,16,NaN,31952.0,28950.0,2021-11-04,0.610,0.553,0.0,54849.0,3
2215,41011,US,OR,Coos County,64487,0.044,other,26.6,NaN,0.91,...,24,NaN,37362.0,34004.0,2021-11-04,0.579,0.527,0.0,70115.0,3
2216,41013,US,OR,Crook County,24404,0.154,other,64.4,NaN,0.79,...,24,NaN,12329.0,11335.0,2021-11-04,0.505,0.464,2.0,23870.0,3
2217,41015,US,OR,Curry County,22925,0.051,other,5.6,NaN,0.75,...,1,NaN,13624.0,11636.0,2021-11-04,0.594,0.508,0.0,24637.0,1
2218,41017,US,OR,Deschutes County,197692,0.116,other,48.3,NaN,0.98,...,51,NaN,133226.0,123137.0,2021-11-04,0.674,0.623,3.0,264203.0,3
2219,41019,US,OR,Douglas County,110980,0.069,other,32.3,NaN,0.96,...,43,NaN,60630.0,54717.0,2021-11-04,0.546,0.493,0.0,101859.0,3
2220,41021,US,OR,Gilliam County,1912,0.071,other,44.8,NaN,NaN,...,2,NaN,878.0,764.0,2021-11-04,0.459,0.400,0.0,1596.0,3
2221,41023,US,OR,Grant County,7199,0.048,other,27.8,NaN,0.66,...,2,NaN,3269.0,3040.0,2021-11-04,0.454,0.422,1.0,5846.0,3
2222,41025,US,OR,Harney County,7393,0.168,other,29.0,NaN,0.55,...,1,NaN,3451.0,3098.0,2021-11-04,0.467,0.419,0.0,6175.0,3
2223,41027,US,OR,Hood River County,23382,0.065,other,20.8,NaN,0.72,...,7,NaN,18937.0,17629.0,2021-11-04,0.810,0.754,0.0,32459.0,3
2224,41029,US,OR,Jackson County,220944,0.081,other,23.9,NaN,1.00,...,41,NaN,128344.0,117363.0,2021-11-04,0.581,0.531,3.0,244801.0,3
2225,41031,US,OR,Jefferson County,24658,0.095,other,57.4,NaN,0.88,...,9,NaN,15213.0,13757.0,2021-11-04,0.617,0.558,1.0,25583.0,3
2226,41033,US,OR,Josephine County,87487,0.051,other,29.4,NaN,1.06,...,27,NaN,44518.0,40908.0,2021-11-04,0.509,0.468,1.0,86543.0,3
2227,41035,US,OR,Klamath County,68238,0.187,other,64.3,NaN,0.99,...,108,NaN,34791.0,31619.0,2021-11-04,0.510,0.463,0.0,62706.0,3
2228,41037,US,OR,Lake County,7869,0.189,other,25.4,NaN,0.65,...,4,NaN,3097.0,2885.0,2021-11-04,0.394,0.367,0.0,5767.0,3
2229,41039,US,OR,Lane County,382067,0.044,other,19.0,NaN,0.90,...,58,NaN,260239.0,240026.0,2021-11-04,0.681,0.628,2.0,508618.0,3
2230,41041,US,OR,Lincoln County,49962,0.044,other,21.4,NaN,0.86,...,11,NaN,35046.0,32553.0,2021-11-04,0.701,0.652,2.0,69004.0,3
2231,41043,US,OR,Linn County,129749,0.071,other,46.7,NaN,0.96,...,37,NaN,71530.0,66580.0,2021-11-04,0.551,0.513,1.0,138789.0,3
2232,41045,US,OR,Malheur County,30571,0.093,other,43.9,NaN,0.80,...,22,NaN,14317.0,12798.0,2021-11-04,0.468,0.419,0.0,22620.0,3
2233,41047,US,OR,Marion County,347818,0.106,other,31.9,NaN,1.00,...,95,NaN,216293.0,197656.0,2021-11-04,0.622,0.568,0.0,415232.0,3
2234,41049,US,OR,Morrow County,11603,0.174,other,32.0,NaN,0.75,...,6,NaN,6250.0,5691.0,2021-11-04,0.539,0.490,0.0,10655.0,3
2235,41051,US,OR,Multnomah County,812855,0.051,other,17.3,NaN,1.04,...,103,NaN,637969.0,580183.0,2021-11-04,0.785,0.714,5.0,1186105.0,3
2236,41053,US,OR,Polk County,86085,0.086,other,30.5,NaN,0.96,...,47,NaN,52816.0,49845.0,2021-11-04,0.614,0.579,0.0,105991.0,3
2237,41055,US,OR,Sherman County,1780,0.247,other,120.4,NaN,NaN,...,7,NaN,1044.0,942.0,2021-11-04,0.587,0.529,0.0,1777.0,3
2238,41057,US,OR,Tillamook County,27036,0.041,other,17.4,NaN,0.82,...,8,NaN,17561.0,16326.0,2021-11-04,0.650,0.604,2.0,33191.0,3
2239,41059,US,OR,Umatilla County,77950,0.104,other,29.5,NaN,0.77,...,32,NaN,43141.0,38719.0,2021-11-04,0.553,0.497,2.0,65298.0,3
2240,41061,US,OR,Union County,26835,0.067,other,30.9,NaN,0.78,...,5,NaN,13036.0,11953.0,2021-11-04,0.486,0.445,0.0,23606.0,3
2241,41063,US,OR,Wallowa County,7208,0.102,other,41.6,NaN,0.75,...,9,NaN,4254.0,3919.0,2021-11-04,0.590,0.544,0.0,7819.0,3
2242,41065,US,OR,Wasco County,26682,0.090,other,42.3,NaN,0.85,...,21,NaN,17235.0,15934.0,2021-11-04,0.646,0.597,0.0,30184.0,3
2243,41067,US,OR,Washington County,601592,0.052,other,15.8,NaN,0.98,...,82,NaN,435495.0,408642.0,2021-11-04,0.724,0.679,2.0,862502.0,3
2244,41069,US,OR,Wheeler County,1332,0.056,other,0.0,NaN,NaN,...,0,NaN,734.0,698.0,2021-11-04,0.551,0.524,0.0,1419.0,1
2245,41071,US,OR,Yamhill County,107100,0.096,other,30.8,NaN,1.04,...,71,NaN,66326.0,61204.0,2021-11-04,0.619,0.571,0.0,124720.0,3

In [21]:
counties_historic = pd.read_csv('counties.timeseries.csv')

In [22]:
ch_df = pd.DataFrame(counties_historic)
ch_df

,date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,...,unused3,unused4,metrics.icuCapacityRatio,riskLevels.overall,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,riskLevels.caseDensity,cdcTransmissionLevel
0,2020-01-22,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
1,2020-01-23,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
2,2020-01-24,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
3,2020-01-25,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
4,2020-01-26,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2084626,2021-10-30,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1109.0,9.0,...,NaN,NaN,NaN,5,0.356,0.31,0.0,NaN,5,3
2084627,2021-10-31,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1109.0,9.0,...,NaN,NaN,NaN,5,0.356,0.31,0.0,NaN,5,3
2084628,2021-11-01,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1121.0,9.0,...,NaN,NaN,NaN,5,0.357,0.32,0.0,NaN,5,3
2084629,2021-11-02,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,1126.0,9.0,...,NaN,NaN,NaN,5,0.357,0.32,0.0,NaN,5,3
2084630,2021-11-03,US,WY,Weston County,56045,NaN,NaN,iso1:us#iso2:us-wy#fips:56045,NaN,NaN,...,NaN,NaN,NaN,5,NaN,0.32,NaN,NaN,5,3

In [28]:
county_list = []
for x in ch_df.columns:
    county_list.append(x)
county_list

['date',
 'country',
 'state',
 'county',
 'fips',
 'lat',
 'long',
 'locationId',
 'actuals.cases',
 'actuals.deaths',
 'actuals.positiveTests',
 'actuals.negativeTests',
 'actuals.contactTracers',
 'actuals.hospitalBeds.capacity',
 'actuals.hospitalBeds.currentUsageTotal',
 'actuals.hospitalBeds.currentUsageCovid',
 'unused1',
 'actuals.icuBeds.capacity',
 'actuals.icuBeds.currentUsageTotal',
 'actuals.icuBeds.currentUsageCovid',
 'unused2',
 'actuals.newCases',
 'actuals.vaccinesDistributed',
 'actuals.vaccinationsInitiated',
 'actuals.vaccinationsCompleted',
 'metrics.testPositivityRatio',
 'metrics.testPositivityRatioDetails',
 'metrics.caseDensity',
 'metrics.contactTracerCapacityRatio',
 'metrics.infectionRate',
 'metrics.infectionRateCI90',
 'unused3',
 'unused4',
 'metrics.icuCapacityRatio',
 'riskLevels.overall',
 'metrics.vaccinationsInitiatedRatio',
 'metrics.vaccinationsCompletedRatio',
 'actuals.newDeaths',
 'actuals.vaccinesAdministered',
 'riskLevels.caseDensity',
 'cdcTransmissionLevel']

In [29]:
li = ['date', 'state', 'county', 'fips', 'actuals.cases', 'actuals.deaths', 'actuals.positiveTests', 'actuals.hospitalBeds.capacity', 'actuals.hospitalBeds.currentUsageTotal', 'actuals.icuBeds.capacity', 'actuals.icuBeds.currentUsageTotal']
for x in li:
    county_list.remove(x)
    
county_list

['country',
 'lat',
 'long',
 'locationId',
 'actuals.negativeTests',
 'actuals.contactTracers',
 'actuals.hospitalBeds.currentUsageCovid',
 'unused1',
 'actuals.icuBeds.currentUsageCovid',
 'unused2',
 'actuals.newCases',
 'actuals.vaccinesDistributed',
 'actuals.vaccinationsInitiated',
 'actuals.vaccinationsCompleted',
 'metrics.testPositivityRatio',
 'metrics.testPositivityRatioDetails',
 'metrics.caseDensity',
 'metrics.contactTracerCapacityRatio',
 'metrics.infectionRate',
 'metrics.infectionRateCI90',
 'unused3',
 'unused4',
 'metrics.icuCapacityRatio',
 'riskLevels.overall',
 'metrics.vaccinationsInitiatedRatio',
 'metrics.vaccinationsCompletedRatio',
 'actuals.newDeaths',
 'actuals.vaccinesAdministered',
 'riskLevels.caseDensity',
 'cdcTransmissionLevel']

In [30]:
ch_df.drop(county_list, axis=1, inplace=True)
ch_df.head()

,date,state,county,fips,actuals.cases,actuals.deaths,actuals.positiveTests,actuals.hospitalBeds.capacity,actuals.hospitalBeds.currentUsageTotal,actuals.icuBeds.capacity,actuals.icuBeds.currentUsageTotal
0,2020-01-22,AK,Aleutians East Borough,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-23,AK,Aleutians East Borough,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-24,AK,Aleutians East Borough,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-25,AK,Aleutians East Borough,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-26,AK,Aleutians East Borough,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
ch_df.isnull().sum()

date                                            0
state                                           0
county                                          0
fips                                            0
actuals.cases                              259479
actuals.deaths                             313604
actuals.positiveTests                     2084029
actuals.hospitalBeds.capacity             1894638
actuals.hospitalBeds.currentUsageTotal    1897520
actuals.icuBeds.capacity                  1962481
actuals.icuBeds.currentUsageTotal         1974630
dtype: int64

In [32]:
ch_df['actuals.hospitalBeds.capacity'].isnull().sum()

1894638

In [35]:
nyt_data = pd.DataFrame(pd.read_csv('us-counties.csv'))
nyt_data

               date      county       state     fips  cases  deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
1888090  2021-11-05  Sweetwater     Wyoming  56037.0   7695    91.0
1888091  2021-11-05       Teton     Wyoming  56039.0   5243    14.0
1888092  2021-11-05       Uinta     Wyoming  56041.0   3901    27.0
1888093  2021-11-05    Washakie     Wyoming  56043.0   1780    35.0
1888094  2021-11-05      Weston     Wyoming  56045.0   1154     9.0

[1888095 rows x 6 columns]

In [34]:
hospital_data_df = pd.DataFrame(pd.read_csv('COVID-19_Reported_Patient_Impact_and_Hospital_Capacity_by_Facility.csv'))

In [4]:
hospital_data_df.isnull().sum()

hospital_pk                                                     0
collection_week                                                 0
state                                                           0
ccn                                                           753
hospital_name                                                   0
                                                            ...
total_personnel_covid_vaccinated_doses_one_7_day           197348
total_personnel_covid_vaccinated_doses_all_7_day           197084
previous_week_patients_covid_vaccinated_doses_one_7_day    197186
previous_week_patients_covid_vaccinated_doses_all_7_day    197128
is_corrected                                                    0
Length: 106, dtype: int64

In [24]:
hospital_data_df.dropna(inplace=True)

In [43]:
hospital_data_df.dtypes

hospital_pk                                                 object
collection_week                                             object
state                                                       object
ccn                                                         object
hospital_name                                               object
                                                            ...
total_personnel_covid_vaccinated_doses_one_7_day           float64
total_personnel_covid_vaccinated_doses_all_7_day           float64
previous_week_patients_covid_vaccinated_doses_one_7_day    float64
previous_week_patients_covid_vaccinated_doses_all_7_day    float64
is_corrected                                                  bool
Length: 106, dtype: object

In [45]:
# Find the data types for the NYT data
nyt_data.dtypes

date       object
county     object
state      object
fips      float64
cases       int64
deaths    float64
dtype: object

In [47]:
# Convert the date column in the NYT data to a datetime object using pd.to_datetime
nyt_data['date'] = pd.to_datetime(nyt_data['date'])
nyt_data.head()

        date     county       state     fips  cases  deaths
0 2020-01-21  Snohomish  Washington  53061.0      1     0.0
1 2020-01-22  Snohomish  Washington  53061.0      1     0.0
2 2020-01-23  Snohomish  Washington  53061.0      1     0.0
3 2020-01-24       Cook    Illinois  17031.0      1     0.0
4 2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [52]:
# Convert the date column in the hospital data to a datetime object using pd.to_datetime
hospital_data_df['collection_week'] = pd.to_datetime(hospital_data_df['collection_week'])
# Check to verify the date is now a datetime object
hospital_data_df.dtypes

hospital_pk                                                        object
collection_week                                            datetime64[ns]
state                                                              object
ccn                                                                object
hospital_name                                                      object
                                                                ...
total_personnel_covid_vaccinated_doses_one_7_day                  float64
total_personnel_covid_vaccinated_doses_all_7_day                  float64
previous_week_patients_covid_vaccinated_doses_one_7_day           float64
previous_week_patients_covid_vaccinated_doses_all_7_day           float64
is_corrected                                                         bool
Length: 106, dtype: object

In [55]:
# The NYT data is already sorted by date
# Sort the hospital data by date
hospital_data_df = hospital_data_df.sort_values(by='collection_week')
hospital_data_df

# The hospital data is binned by collection week ending on every friday

,hospital_pk,collection_week,state,ccn,hospital_name,address,city,zip,hospital_subtype,fips_code,...,previous_day_admission_pediatric_covid_confirmed_7_day_coverage,previous_day_admission_adult_covid_suspected_7_day_coverage,previous_day_admission_pediatric_covid_suspected_7_day_coverage,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected
324747,110045,2020-07-31,GA,110045,NORTHEAST GEORGIA MEDICAL CENTER BARROW,316 NORTH BROAD STREET,WINDER,30680.0,Short Term,13013.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False
319394,440018,2020-07-31,TN,440018,SYCAMORE SHOALS HOSPITAL,1501 WEST ELK AVENUE,ELIZABETHTON,37643.0,Short Term,47019.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
315259,450565,2020-07-31,TX,450565,PALO PINTO GENERAL HOSPITAL,400 SOUTHWEST 25 AVE,MINERAL WELLS,76067.0,Short Term,48363.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
319367,180045,2020-07-31,KY,180045,ST ELIZABETH FLORENCE,4900 HOUSTON ROAD,FLORENCE,41042.0,Short Term,21015.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
319371,100168,2020-07-31,FL,100168,BOCA RATON REGIONAL HOSPITAL,800 MEADOWS RD,BOCA RATON,33486.0,Short Term,12099.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,310032,2021-10-22,NJ,310032,INSPIRA MEDICAL CENTER VINELAND,1505 W SHERMAN AVE,VINELAND,8360.0,Short Term,34011.0,...,7,7,7,19.0,737.0,174.0,5443.0,120.0,99.0,False
10378,341320,2021-10-22,NC,341320,ALLEGHANY COUNTY MEMORIAL HOSPITAL,617 DOCTORS STREET,SPARTA,28675.0,Critical Access Hospitals,37005.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
10377,451311,2021-10-22,TX,451311,SWEENY COMMUNITY HOSPITAL,305 NORTH MCKINNEY,SWEENY,77480.0,Critical Access Hospitals,48039.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
10385,281329,2021-10-22,NE,281329,AVERA ST ANTHONY'S HOSPITAL,300 NORTH 2ND ST,O' NEILL,68763.0,Critical Access Hospitals,31089.0,...,7,7,7,0.0,0.0,148.0,148.0,0.0,0.0,False
10352,110030,2021-10-22,GA,110030,PIEDMONT CARTERSVILLE MEDICAL CENTER,960 JOE FRANK HARRIS PARKWAY,CARTERSVILLE,30120.0,Short Term,13015.0,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False

In [64]:
# 1. Remove the data for dates before 7-31-20 and after 10-22-21
# 2. Bin the date column by weeks ending every friday
# 3. Sum the cases and deaths columns for each week binned

# Step 1:
nyt_data_filtered = nyt_data[nyt_data['date'] >= '2020-07-25']
nyt_data_filtered = nyt_data_filtered[nyt_data_filtered['date'] <= '2021-10-22']
nyt_data_filtered

              date      county    state     fips  cases  deaths
366652  2020-07-25     Autauga  Alabama   1001.0    932    21.0
366653  2020-07-25     Baldwin  Alabama   1003.0   2662    18.0
366654  2020-07-25     Barbour  Alabama   1005.0    552     4.0
366655  2020-07-25        Bibb  Alabama   1007.0    318     2.0
366656  2020-07-25      Blount  Alabama   1009.0    637     1.0
...            ...         ...      ...      ...    ...     ...
1842600 2021-10-22  Sweetwater  Wyoming  56037.0   7414    79.0
1842601 2021-10-22       Teton  Wyoming  56039.0   5119    14.0
1842602 2021-10-22       Uinta  Wyoming  56041.0   3781    26.0
1842603 2021-10-22    Washakie  Wyoming  56043.0   1676    33.0
1842604 2021-10-22      Weston  Wyoming  56045.0   1027     9.0

[1475953 rows x 6 columns]

In [73]:
# Step 2:
# Step 3:
columns_to_sum = [nyt_data_filtered['cases'], nyt_data_filtered['deaths']]
nyt_data_grouped = nyt_data_filtered.groupby(['fips', pd.Grouper(key='date', freq='W-FRI')]).agg({'cases':'sum','deaths':'sum'}).reset_index()
nyt_data_grouped

           fips       date  cases  deaths
0        1001.0 2020-07-31   6817   147.0
1        1001.0 2020-08-07   7503   150.0
2        1001.0 2020-08-14   8531   158.0
3        1001.0 2020-08-21   9009   161.0
4        1001.0 2020-08-28   9484   161.0
...         ...        ...    ...     ...
208977  78030.0 2021-09-24  24720   297.0
208978  78030.0 2021-10-01  24982   304.0
208979  78030.0 2021-10-08  25204   308.0
208980  78030.0 2021-10-15  25290   311.0
208981  78030.0 2021-10-22  25435   315.0

[208982 rows x 4 columns]

In [77]:
# Resort the nyt_data_grouped by date
nyt_data_grouped = nyt_data_grouped.sort_values(by='date')
nyt_data_grouped

           fips       date   cases  deaths
0        1001.0 2020-07-31    6817   147.0
32676   13241.0 2020-07-31    1161    21.0
167287  48121.0 2020-07-31   44680   448.0
32611   13239.0 2020-07-31     185     7.0
167352  48123.0 2020-07-31    3578    90.0
...         ...        ...     ...     ...
125642  37103.0 2021-10-22    9157   207.0
107818  31015.0 2021-10-22    1623    21.0
195136  54039.0 2021-10-22  167528  3191.0
142932  40153.0 2021-10-22   25980   322.0
208981  78030.0 2021-10-22   25435   315.0

[208982 rows x 4 columns]

In [80]:
# Read in the vaccination data and complete the data cleaning steps as outlined above
vaccine_df = pd.DataFrame(pd.read_csv('COVID-19_Vaccinations_in_the_United_States_County.csv'))
vaccine_df

,Date,FIPS,MMWR_week,Recip_County,Recip_State,Series_Complete_Pop_Pct,Series_Complete_Yes,Series_Complete_12Plus,Series_Complete_12PlusPop_Pct,Series_Complete_18Plus,...,SVI_CTGY,Series_Complete_Pop_Pct_SVI,Series_Complete_12PlusPop_Pct_SVI,Series_Complete_18PlusPop_Pct_SVI,Series_Complete_65PlusPop_Pct_SVI,Metro_status,Series_Complete_Pop_Pct_UR_Equity,Series_Complete_12PlusPop_Pct_UR_Equity,Series_Complete_18PlusPop_Pct_UR_Equity,Series_Complete_65PlusPop_Pct_UR_Equity
0,11/06/2021,21097,44,Harrison County,KY,43.2,8163,8163.0,50.7,7772,...,C,11.0,12.0,12.0,12.0,Non-metro,7.0,8.0,8.0,8.0
1,11/06/2021,18105,44,Monroe County,IN,54.7,81158,81155.0,61.0,76819,...,B,8.0,8.0,8.0,8.0,Metro,4.0,4.0,4.0,4.0
2,11/06/2021,46023,44,Charles Mix County,SD,47.3,4399,4398.0,59.8,4119,...,C,11.0,12.0,12.0,12.0,Non-metro,7.0,8.0,8.0,8.0
3,11/06/2021,41045,44,Malheur County,OR,42.2,12893,12884.0,51.1,12170,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
4,11/06/2021,39127,44,Perry County,OH,36.9,13339,13339.0,43.5,12823,...,C,10.0,11.0,11.0,12.0,Metro,2.0,3.0,3.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079793,12/13/2020,45045,51,Greenville County,SC,0.0,0,0.0,0.0,0,...,C,NaN,NaN,NaN,NaN,Metro,NaN,NaN,NaN,NaN
1079794,12/13/2020,05145,51,White County,AR,0.0,0,0.0,0.0,0,...,C,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN
1079795,12/13/2020,55025,51,Dane County,WI,0.0,0,0.0,0.0,0,...,A,NaN,NaN,NaN,NaN,Metro,NaN,NaN,NaN,NaN
1079796,12/13/2020,18109,51,Morgan County,IN,0.0,0,0.0,0.0,0,...,A,NaN,NaN,NaN,NaN,Metro,NaN,NaN,NaN,NaN
1079797,12/13/2020,72119,51,Rio Grande Municipio,PR,0.0,0,0.0,0.0,0,...,C,NaN,NaN,NaN,NaN,Metro,NaN,NaN,NaN,NaN

In [82]:
# Get the data types for the vaccination data set
vaccine_df.dtypes

Date                                        object
FIPS                                        object
MMWR_week                                    int64
Recip_County                                object
Recip_State                                 object
Series_Complete_Pop_Pct                    float64
Series_Complete_Yes                          int64
Series_Complete_12Plus                     float64
Series_Complete_12PlusPop_Pct              float64
Series_Complete_18Plus                       int64
Series_Complete_18PlusPop_Pct              float64
Series_Complete_65Plus                       int64
Series_Complete_65PlusPop_Pct              float64
Completeness_pct                           float64
Administered_Dose1_Recip                   float64
Administered_Dose1_Pop_Pct                 float64
Administered_Dose1_Recip_12Plus            float64
Administered_Dose1_Recip_12PlusPop_Pct     float64
Administered_Dose1_Recip_18Plus            float64
Administered_Dose1_Recip_18PlusPop_Pct     float64
Administered_Dose1_Recip_65Plus            float64
Administered_Dose1_Recip_65PlusPop_Pct     float64
SVI_CTGY                                    object
Series_Complete_Pop_Pct_SVI                float64
Series_Complete_12PlusPop_Pct_SVI          float64
Series_Complete_18PlusPop_Pct_SVI          float64
Series_Complete_65PlusPop_Pct_SVI          float64
Metro_status                                object
Series_Complete_Pop_Pct_UR_Equity          float64
Series_Complete_12PlusPop_Pct_UR_Equity    float64
Series_Complete_18PlusPop_Pct_UR_Equity    float64
Series_Complete_65PlusPop_Pct_UR_Equity    float64
dtype: object

In [86]:
# Convert the date column to a pandas datetime
vaccine_df['Date'] = pd.to_datetime(vaccine_df['Date'])
vaccine_df.dtypes

Date                                       datetime64[ns]
FIPS                                               object
MMWR_week                                           int64
Recip_County                                       object
Recip_State                                        object
Series_Complete_Pop_Pct                           float64
Series_Complete_Yes                                 int64
Series_Complete_12Plus                            float64
Series_Complete_12PlusPop_Pct                     float64
Series_Complete_18Plus                              int64
Series_Complete_18PlusPop_Pct                     float64
Series_Complete_65Plus                              int64
Series_Complete_65PlusPop_Pct                     float64
Completeness_pct                                  float64
Administered_Dose1_Recip                          float64
Administered_Dose1_Pop_Pct                        float64
Administered_Dose1_Recip_12Plus                   float64
Administered_Dose1_Recip_12PlusPop_Pct            float64
Administered_Dose1_Recip_18Plus                   float64
Administered_Dose1_Recip_18PlusPop_Pct            float64
Administered_Dose1_Recip_65Plus                   float64
Administered_Dose1_Recip_65PlusPop_Pct            float64
SVI_CTGY                                           object
Series_Complete_Pop_Pct_SVI                       float64
Series_Complete_12PlusPop_Pct_SVI                 float64
Series_Complete_18PlusPop_Pct_SVI                 float64
Series_Complete_65PlusPop_Pct_SVI                 float64
Metro_status                                       object
Series_Complete_Pop_Pct_UR_Equity                 float64
Series_Complete_12PlusPop_Pct_UR_Equity           float64
Series_Complete_18PlusPop_Pct_UR_Equity           float64
Series_Complete_65PlusPop_Pct_UR_Equity           float64
dtype: object

In [89]:
or_state = vaccine_df[vaccine_df['Recip_State'] == 'OR']
or_umatilla = or_state[or_state['Recip_County'] == 'Umatilla County']
or_umatilla

,Date,FIPS,MMWR_week,Recip_County,Recip_State,Series_Complete_Pop_Pct,Series_Complete_Yes,Series_Complete_12Plus,Series_Complete_12PlusPop_Pct,Series_Complete_18Plus,...,SVI_CTGY,Series_Complete_Pop_Pct_SVI,Series_Complete_12PlusPop_Pct_SVI,Series_Complete_18PlusPop_Pct_SVI,Series_Complete_65PlusPop_Pct_SVI,Metro_status,Series_Complete_Pop_Pct_UR_Equity,Series_Complete_12PlusPop_Pct_UR_Equity,Series_Complete_18PlusPop_Pct_UR_Equity,Series_Complete_65PlusPop_Pct_UR_Equity
17,2021-11-06,41059,44,Umatilla County,OR,49.9,38931,38891.0,59.7,36228,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
3599,2021-11-05,41059,44,Umatilla County,OR,49.9,38869,38829.0,59.6,36171,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
6724,2021-11-04,41059,44,Umatilla County,OR,49.8,38829,38789.0,59.5,36135,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
12492,2021-11-03,41059,44,Umatilla County,OR,49.7,38763,38723.0,59.4,36077,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
14323,2021-11-02,41059,44,Umatilla County,OR,49.7,38719,38679.0,59.4,36034,...,D,15.0,16.0,16.0,16.0,Non-metro,7.0,8.0,8.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064759,2020-12-17,41059,51,Umatilla County,OR,0.0,0,0.0,0.0,0,...,D,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN
1067481,2020-12-16,41059,51,Umatilla County,OR,0.0,0,0.0,0.0,0,...,D,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN
1070824,2020-12-15,41059,51,Umatilla County,OR,0.0,0,0.0,0.0,0,...,D,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN
1075975,2020-12-14,41059,51,Umatilla County,OR,0.0,0,0.0,0.0,0,...,D,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN
1079719,2020-12-13,41059,51,Umatilla County,OR,0.0,0,0.0,0.0,0,...,D,NaN,NaN,NaN,NaN,Non-metro,NaN,NaN,NaN,NaN

In [94]:
or_umatilla = or_umatilla.groupby(['FIPS', pd.Grouper(key='Date', freq='W-FRI')]).agg({'Series_Complete_Yes':lambda g: g.iloc[0] - g.iloc[-1]}).reset_index()
or_umatilla.sort_values('Date', inplace=True)
or_umatilla

     FIPS       Date  Series_Complete_Yes
0   41059 2020-12-18                    0
1   41059 2020-12-25                    0
2   41059 2021-01-01                    0
3   41059 2021-01-08                    0
4   41059 2021-01-15                    0
5   41059 2021-01-22                    0
6   41059 2021-01-29                    0
7   41059 2021-02-05                    0
8   41059 2021-02-12                    0
9   41059 2021-02-19                    0
10  41059 2021-02-26                    0
11  41059 2021-03-05                    0
12  41059 2021-03-12                    0
13  41059 2021-03-19                    0
14  41059 2021-03-26                    0
15  41059 2021-04-02                    0
16  41059 2021-04-09                    0
17  41059 2021-04-16                    0
18  41059 2021-04-23                    0
19  41059 2021-04-30                    0
20  41059 2021-05-07                    0
21  41059 2021-05-14                    0
22  41059 2021-05-21                    0
23  41059 2021-05-28                    0
24  41059 2021-06-04                    0
25  41059 2021-06-11                    0
26  41059 2021-06-18                    0
27  41059 2021-06-25                    0
28  41059 2021-07-02                    0
29  41059 2021-07-09                    0
30  41059 2021-07-16                    0
31  41059 2021-07-23                    0
32  41059 2021-07-30                    0
33  41059 2021-08-06                    0
34  41059 2021-08-13                    0
35  41059 2021-08-20                    0
36  41059 2021-08-27                    0
37  41059 2021-09-03                    0
38  41059 2021-09-10                    0
39  41059 2021-09-17                    0
40  41059 2021-09-24                    0
41  41059 2021-10-01                    0
42  41059 2021-10-08                    0
43  41059 2021-10-15                    0
44  41059 2021-10-22                    0
45  41059 2021-10-29                    0
46  41059 2021-11-05                    0
47  41059 2021-11-12                    0

In [106]:
merged_df = pd.concat([hospital_data_df, nyt_data_grouped], join='outer').reset_index()
merged_df

,index,hospital_pk,collection_week,state,ccn,hospital_name,address,city,zip,hospital_subtype,...,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected,fips,date,cases,deaths
0,324747,110045,2020-07-31,GA,110045,NORTHEAST GEORGIA MEDICAL CENTER BARROW,316 NORTH BROAD STREET,WINDER,30680.0,Short Term,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaT,NaN,NaN
1,319394,440018,2020-07-31,TN,440018,SYCAMORE SHOALS HOSPITAL,1501 WEST ELK AVENUE,ELIZABETHTON,37643.0,Short Term,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaT,NaN,NaN
2,315259,450565,2020-07-31,TX,450565,PALO PINTO GENERAL HOSPITAL,400 SOUTHWEST 25 AVE,MINERAL WELLS,76067.0,Short Term,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaT,NaN,NaN
3,319367,180045,2020-07-31,KY,180045,ST ELIZABETH FLORENCE,4900 HOUSTON ROAD,FLORENCE,41042.0,Short Term,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaT,NaN,NaN
4,319371,100168,2020-07-31,FL,100168,BOCA RATON REGIONAL HOSPITAL,800 MEADOWS RD,BOCA RATON,33486.0,Short Term,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533725,125642,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,37103.0,2021-10-22,9157.0,207.0
533726,107818,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31015.0,2021-10-22,1623.0,21.0
533727,195136,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,54039.0,2021-10-22,167528.0,3191.0
533728,142932,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40153.0,2021-10-22,25980.0,322.0
533729,208981,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,78030.0,2021-10-22,25435.0,315.0

In [107]:
nyt_data_grouped.nunique()

fips       3218
date         65
cases     74577
deaths    10167
dtype: int64

In [117]:
hospital_data_df.nunique()

hospital_pk                                                5072
collection_week                                              65
state                                                        56
ccn                                                        5047
hospital_name                                              4919
                                                           ...
total_personnel_covid_vaccinated_doses_one_7_day           5538
total_personnel_covid_vaccinated_doses_all_7_day           7025
previous_week_patients_covid_vaccinated_doses_one_7_day    3153
previous_week_patients_covid_vaccinated_doses_all_7_day    3262
is_corrected                                                  2
Length: 106, dtype: int64

In [122]:
hospital_data_df.rename(columns={'collection_week': 'date', 'zip': 'fips'}, inplace=True)
hospital_data_df.fips.nunique()

4465

In [124]:
m_df = nyt_data_grouped.merge(hospital_data_df, on='fips')
m_df

,fips,date_x,cases,deaths,hospital_pk,date_y,state,ccn,hospital_name,address,...,previous_day_admission_pediatric_covid_confirmed_7_day_coverage,previous_day_admission_adult_covid_suspected_7_day_coverage,previous_day_admission_pediatric_covid_suspected_7_day_coverage,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected
0,48135.0,2020-07-31,21562,294.0,230244,2020-07-31,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
1,48135.0,2020-07-31,21562,294.0,230244,2020-08-07,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,False
2,48135.0,2020-07-31,21562,294.0,230244,2020-08-14,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,6,6,6,NaN,NaN,NaN,NaN,NaN,NaN,False
3,48135.0,2020-07-31,21562,294.0,230244,2020-08-21,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
4,48135.0,2020-07-31,21562,294.0,230244,2020-08-28,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914935,48033.0,2021-10-22,294,14.0,230071,2021-09-24,MI,230071,STRAITH HOSPITAL FOR SPECIAL SURGERY,23901 LAHSER,...,7,7,7,0.0,53.0,0.0,66.0,0.0,0.0,False
914936,48033.0,2021-10-22,294,14.0,230071,2021-10-01,MI,230071,STRAITH HOSPITAL FOR SPECIAL SURGERY,23901 LAHSER,...,7,7,7,0.0,39.0,-999999.0,66.0,0.0,0.0,False
914937,48033.0,2021-10-22,294,14.0,230071,2021-10-08,MI,230071,STRAITH HOSPITAL FOR SPECIAL SURGERY,23901 LAHSER,...,7,7,7,0.0,37.0,-999999.0,68.0,0.0,0.0,False
914938,48033.0,2021-10-22,294,14.0,230071,2021-10-15,MI,230071,STRAITH HOSPITAL FOR SPECIAL SURGERY,23901 LAHSER,...,7,7,7,0.0,37.0,-999999.0,68.0,0.0,0.0,False
914939,48033.0,2021-10-22,294,14.0,230071,2021-10-22,MI,230071,STRAITH HOSPITAL FOR SPECIAL SURGERY,23901 LAHSER,...,6,6,6,0.0,35.0,-999999.0,68.0,0.0,0.0,False

In [126]:
m_df.isnull().sum()

fips                                                            0
date_x                                                          0
cases                                                           0
deaths                                                          0
hospital_pk                                                     0
                                                            ...
total_personnel_covid_vaccinated_doses_one_7_day           516363
total_personnel_covid_vaccinated_doses_all_7_day           516428
previous_week_patients_covid_vaccinated_doses_one_7_day    517533
previous_week_patients_covid_vaccinated_doses_all_7_day    516623
is_corrected                                                    0
Length: 109, dtype: int64

In [128]:
m_df.dropna().head(50)

,fips,date_x,cases,deaths,hospital_pk,date_y,state,ccn,hospital_name,address,...,previous_day_admission_pediatric_covid_confirmed_7_day_coverage,previous_day_admission_adult_covid_suspected_7_day_coverage,previous_day_admission_pediatric_covid_suspected_7_day_coverage,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected
24,48135.0,2020-07-31,21562,294.0,230244,2021-01-15,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,297.0,837.0,203.0,521.0,78.0,10.0,False
25,48135.0,2020-07-31,21562,294.0,230244,2021-01-22,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,111.0,809.0,178.0,576.0,5.0,6.0,False
26,48135.0,2020-07-31,21562,294.0,230244,2021-01-29,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,38.0,796.0,177.0,589.0,-999999.0,-999999.0,False
27,48135.0,2020-07-31,21562,294.0,230244,2021-02-05,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,769.0,798.0,175.0,594.0,-999999.0,5.0,False
28,48135.0,2020-07-31,21562,294.0,230244,2021-02-12,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,9.0,729.0,171.0,600.0,0.0,0.0,False
29,48135.0,2020-07-31,21562,294.0,230244,2021-02-19,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,36.0,723.0,156.0,625.0,-999999.0,6.0,False
30,48135.0,2020-07-31,21562,294.0,230244,2021-02-26,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,5.0,724.0,155.0,628.0,0.0,0.0,False
31,48135.0,2020-07-31,21562,294.0,230244,2021-03-05,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,26.0,723.0,153.0,642.0,0.0,0.0,False
32,48135.0,2020-07-31,21562,294.0,230244,2021-03-12,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,20.0,716.0,167.0,645.0,0.0,0.0,False
33,48135.0,2020-07-31,21562,294.0,230244,2021-03-19,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,13.0,713.0,176.0,647.0,0.0,0.0,False
34,48135.0,2020-07-31,21562,294.0,230244,2021-03-26,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,15.0,709.0,183.0,651.0,0.0,0.0,False
35,48135.0,2020-07-31,21562,294.0,230244,2021-04-02,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,713.0,183.0,651.0,0.0,0.0,False
36,48135.0,2020-07-31,21562,294.0,230244,2021-04-09,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,31.0,701.0,194.0,660.0,0.0,0.0,False
37,48135.0,2020-07-31,21562,294.0,230244,2021-04-16,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,19.0,702.0,189.0,672.0,0.0,0.0,False
38,48135.0,2020-07-31,21562,294.0,230244,2021-04-23,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,5.0,710.0,188.0,675.0,0.0,0.0,False
39,48135.0,2020-07-31,21562,294.0,230244,2021-04-30,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,24.0,713.0,174.0,694.0,0.0,0.0,False
40,48135.0,2020-07-31,21562,294.0,230244,2021-05-07,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,12.0,718.0,168.0,702.0,0.0,0.0,False
41,48135.0,2020-07-31,21562,294.0,230244,2021-05-14,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,729.0,168.0,702.0,0.0,0.0,False
42,48135.0,2020-07-31,21562,294.0,230244,2021-05-21,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,15.0,737.0,162.0,713.0,0.0,0.0,False
43,48135.0,2020-07-31,21562,294.0,230244,2021-05-28,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,9.0,741.0,159.0,719.0,33.0,157.0,False
44,48135.0,2020-07-31,21562,294.0,230244,2021-06-04,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,747.0,159.0,720.0,10.0,31.0,False
45,48135.0,2020-07-31,21562,294.0,230244,2021-06-11,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,778.0,159.0,720.0,22.0,36.0,False
46,48135.0,2020-07-31,21562,294.0,230244,2021-06-18,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,7.0,782.0,156.0,725.0,12.0,19.0,False
47,48135.0,2020-07-31,21562,294.0,230244,2021-06-25,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,791.0,156.0,725.0,8.0,37.0,False
48,48135.0,2020-07-31,21562,294.0,230244,2021-07-02,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,802.0,155.0,727.0,-999999.0,18.0,False
49,48135.0,2020-07-31,21562,294.0,230244,2021-07-09,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,802.0,155.0,727.0,-999999.0,18.0,False
50,48135.0,2020-07-31,21562,294.0,230244,2021-07-16,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,822.0,155.0,727.0,4.0,12.0,False
51,48135.0,2020-07-31,21562,294.0,230244,2021-07-23,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,5.0,835.0,156.0,729.0,5.0,25.0,False
52,48135.0,2020-07-31,21562,294.0,230244,2021-07-30,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,848.0,157.0,729.0,-999999.0,11.0,False
53,48135.0,2020-07-31,21562,294.0,230244,2021-08-06,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,0.0,848.0,157.0,729.0,-999999.0,11.0,False
54,48135.0,2020-07-31,21562,294.0,230244,2021-08-13,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,728.0,158.0,731.0,-999999.0,-999999.0,False
55,48135.0,2020-07-31,21562,294.0,230244,2021-08-20,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,728.0,158.0,731.0,-999999.0,-999999.0,False
56,48135.0,2020-07-31,21562,294.0,230244,2021-08-27,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,728.0,158.0,731.0,-999999.0,-999999.0,False
57,48135.0,2020-07-31,21562,294.0,230244,2021-09-03,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,488.0,160.0,734.0,4.0,-999999.0,False
58,48135.0,2020-07-31,21562,294.0,230244,2021-09-10,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,482.0,159.0,736.0,4.0,-999999.0,False
59,48135.0,2020-07-31,21562,294.0,230244,2021-09-17,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,478.0,160.0,736.0,-999999.0,4.0,False
60,48135.0,2020-07-31,21562,294.0,230244,2021-09-24,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,480.0,158.0,738.0,-999999.0,6.0,False
61,48135.0,2020-07-31,21562,294.0,230244,2021-10-01,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,491.0,157.0,739.0,0.0,4.0,False
62,48135.0,2020-07-31,21562,294.0,230244,2021-10-08,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,507.0,156.0,740.0,0.0,-999999.0,False
63,48135.0,2020-07-31,21562,294.0,230244,2021-10-15,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,-999999.0,517.0,154.0,742.0,0.0,-999999.0,False
64,48135.0,2020-07-31,21562,294.0,230244,2021-10-22,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,52.0,520.0,153.0,696.0,0.0,-999999.0,False
89,48135.0,2020-08-07,23947,363.0,230244,2021-01-15,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,297.0,837.0,203.0,521.0,78.0,10.0,False
90,48135.0,2020-08-07,23947,363.0,230244,2021-01-22,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,111.0,809.0,178.0,576.0,5.0,6.0,False
91,48135.0,2020-08-07,23947,363.0,230244,2021-01-29,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,38.0,796.0,177.0,589.0,-999999.0,-999999.0,False
92,48135.0,2020-08-07,23947,363.0,230244,2021-02-05,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,769.0,798.0,175.0,594.0,-999999.0,5.0,False
93,48135.0,2020-08-07,23947,363.0,230244,2021-02-12,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,9.0,729.0,171.0,600.0,0.0,0.0,False
94,48135.0,2020-08-07,23947,363.0,230244,2021-02-19,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,36.0,723.0,156.0,625.0,-999999.0,6.0,False
95,48135.0,2020-08-07,23947,363.0,230244,2021-02-26,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,5.0,724.0,155.0,628.0,0.0,0.0,False
96,48135.0,2020-08-07,23947,363.0,230244,2021-03-05,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,26.0,723.0,153.0,642.0,0.0,0.0,False
97,48135.0,2020-08-07,23947,363.0,230244,2021-03-12,MI,230244,GARDEN CITY HOSPITAL,6245 INKSTER RD,...,7,7,7,20.0,716.0,167.0,645.0,0.0,0.0,False

In [137]:
# Set each column to a string value so we can concatonate them together 
nyt_data_grouped['fips'] = nyt_data_grouped['fips'].astype('str')
nyt_data_grouped['date'] = nyt_data_grouped['date'].astype('str')
nyt_data_grouped['fips'].dtype

dtype('O')

In [138]:
# Concatonate the date column and the fips column to create fips_date
nyt_data_grouped['fips_date'] = nyt_data_grouped['fips'] + nyt_data_grouped['date']
nyt_data_grouped

           fips        date   cases  deaths          fips_date
0        1001.0  2020-07-31    6817   147.0   1001.02020-07-31
32676   13241.0  2020-07-31    1161    21.0  13241.02020-07-31
167287  48121.0  2020-07-31   44680   448.0  48121.02020-07-31
32611   13239.0  2020-07-31     185     7.0  13239.02020-07-31
167352  48123.0  2020-07-31    3578    90.0  48123.02020-07-31
...         ...         ...     ...     ...                ...
125642  37103.0  2021-10-22    9157   207.0  37103.02021-10-22
107818  31015.0  2021-10-22    1623    21.0  31015.02021-10-22
195136  54039.0  2021-10-22  167528  3191.0  54039.02021-10-22
142932  40153.0  2021-10-22   25980   322.0  40153.02021-10-22
208981  78030.0  2021-10-22   25435   315.0  78030.02021-10-22

[208982 rows x 5 columns]

In [145]:
nyt_data_grouped.nunique()

fips           3218
date             65
cases         74577
deaths        10167
fips_date    208982
dtype: int64

In [142]:
# Convert the hospital date and fips_code column to strings
hospital_data_df['date'] = hospital_data_df['date'].astype('str')
hospital_data_df['fips_code'] = hospital_data_df['fips_code'].astype('str')

In [143]:
# Concat the date and fips_code for new columns fips_date
hospital_data_df['fips_date'] = hospital_data_df['fips_code'] + hospital_data_df['date']
hospital_data_df

,hospital_pk,date,state,ccn,hospital_name,address,city,fips,hospital_subtype,fips_code,...,previous_day_admission_adult_covid_suspected_7_day_coverage,previous_day_admission_pediatric_covid_suspected_7_day_coverage,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected,fips_date
324747,110045,2020-07-31,GA,110045,NORTHEAST GEORGIA MEDICAL CENTER BARROW,316 NORTH BROAD STREET,WINDER,30680.0,Short Term,13013.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False,13013.02020-07-31
319394,440018,2020-07-31,TN,440018,SYCAMORE SHOALS HOSPITAL,1501 WEST ELK AVENUE,ELIZABETHTON,37643.0,Short Term,47019.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,47019.02020-07-31
315259,450565,2020-07-31,TX,450565,PALO PINTO GENERAL HOSPITAL,400 SOUTHWEST 25 AVE,MINERAL WELLS,76067.0,Short Term,48363.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,48363.02020-07-31
319367,180045,2020-07-31,KY,180045,ST ELIZABETH FLORENCE,4900 HOUSTON ROAD,FLORENCE,41042.0,Short Term,21015.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,21015.02020-07-31
319371,100168,2020-07-31,FL,100168,BOCA RATON REGIONAL HOSPITAL,800 MEADOWS RD,BOCA RATON,33486.0,Short Term,12099.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,12099.02020-07-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,310032,2021-10-22,NJ,310032,INSPIRA MEDICAL CENTER VINELAND,1505 W SHERMAN AVE,VINELAND,8360.0,Short Term,34011.0,...,7,7,19.0,737.0,174.0,5443.0,120.0,99.0,False,34011.02021-10-22
10378,341320,2021-10-22,NC,341320,ALLEGHANY COUNTY MEMORIAL HOSPITAL,617 DOCTORS STREET,SPARTA,28675.0,Critical Access Hospitals,37005.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,37005.02021-10-22
10377,451311,2021-10-22,TX,451311,SWEENY COMMUNITY HOSPITAL,305 NORTH MCKINNEY,SWEENY,77480.0,Critical Access Hospitals,48039.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,48039.02021-10-22
10385,281329,2021-10-22,NE,281329,AVERA ST ANTHONY'S HOSPITAL,300 NORTH 2ND ST,O' NEILL,68763.0,Critical Access Hospitals,31089.0,...,7,7,0.0,0.0,148.0,148.0,0.0,0.0,False,31089.02021-10-22
10352,110030,2021-10-22,GA,110030,PIEDMONT CARTERSVILLE MEDICAL CENTER,960 JOE FRANK HARRIS PARKWAY,CARTERSVILLE,30120.0,Short Term,13015.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,13015.02021-10-22

In [144]:
hospital_data_df.nunique()

hospital_pk                                                  5072
date                                                           65
state                                                          56
ccn                                                          5047
hospital_name                                                4919
                                                            ...
total_personnel_covid_vaccinated_doses_all_7_day             7025
previous_week_patients_covid_vaccinated_doses_one_7_day      3153
previous_week_patients_covid_vaccinated_doses_all_7_day      3262
is_corrected                                                    2
fips_date                                                  159936
Length: 107, dtype: int64

In [147]:
hospital_data_df

,hospital_pk,date,state,ccn,hospital_name,address,city,fips,hospital_subtype,fips_code,...,previous_day_admission_adult_covid_suspected_7_day_coverage,previous_day_admission_pediatric_covid_suspected_7_day_coverage,previous_week_personnel_covid_vaccinated_doses_administered_7_day,total_personnel_covid_vaccinated_doses_none_7_day,total_personnel_covid_vaccinated_doses_one_7_day,total_personnel_covid_vaccinated_doses_all_7_day,previous_week_patients_covid_vaccinated_doses_one_7_day,previous_week_patients_covid_vaccinated_doses_all_7_day,is_corrected,fips_date
324747,110045,2020-07-31,GA,110045,NORTHEAST GEORGIA MEDICAL CENTER BARROW,316 NORTH BROAD STREET,WINDER,30680.0,Short Term,13013.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,False,13013.02020-07-31
319394,440018,2020-07-31,TN,440018,SYCAMORE SHOALS HOSPITAL,1501 WEST ELK AVENUE,ELIZABETHTON,37643.0,Short Term,47019.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,47019.02020-07-31
315259,450565,2020-07-31,TX,450565,PALO PINTO GENERAL HOSPITAL,400 SOUTHWEST 25 AVE,MINERAL WELLS,76067.0,Short Term,48363.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,48363.02020-07-31
319367,180045,2020-07-31,KY,180045,ST ELIZABETH FLORENCE,4900 HOUSTON ROAD,FLORENCE,41042.0,Short Term,21015.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,21015.02020-07-31
319371,100168,2020-07-31,FL,100168,BOCA RATON REGIONAL HOSPITAL,800 MEADOWS RD,BOCA RATON,33486.0,Short Term,12099.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,12099.02020-07-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10380,310032,2021-10-22,NJ,310032,INSPIRA MEDICAL CENTER VINELAND,1505 W SHERMAN AVE,VINELAND,8360.0,Short Term,34011.0,...,7,7,19.0,737.0,174.0,5443.0,120.0,99.0,False,34011.02021-10-22
10378,341320,2021-10-22,NC,341320,ALLEGHANY COUNTY MEMORIAL HOSPITAL,617 DOCTORS STREET,SPARTA,28675.0,Critical Access Hospitals,37005.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,37005.02021-10-22
10377,451311,2021-10-22,TX,451311,SWEENY COMMUNITY HOSPITAL,305 NORTH MCKINNEY,SWEENY,77480.0,Critical Access Hospitals,48039.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,48039.02021-10-22
10385,281329,2021-10-22,NE,281329,AVERA ST ANTHONY'S HOSPITAL,300 NORTH 2ND ST,O' NEILL,68763.0,Critical Access Hospitals,31089.0,...,7,7,0.0,0.0,148.0,148.0,0.0,0.0,False,31089.02021-10-22
10352,110030,2021-10-22,GA,110030,PIEDMONT CARTERSVILLE MEDICAL CENTER,960 JOE FRANK HARRIS PARKWAY,CARTERSVILLE,30120.0,Short Term,13015.0,...,7,7,NaN,NaN,NaN,NaN,NaN,NaN,False,13015.02021-10-22

In [179]:
# Create a new df to groupby the new fips_date column so each row is unique
hospital_data_df2 = hospital_data_df.groupby(['fips_date']).agg({'total_beds_7_day_sum':'sum','all_adult_hospital_beds_7_day_sum':'sum', 'all_adult_hospital_inpatient_beds_7_day_sum':'sum', 'inpatient_beds_used_7_day_sum':'sum', 'all_adult_hospital_inpatient_bed_occupied_7_day_sum':'sum', 
                                                                                                                       'total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum':'sum', 'total_adult_patients_hospitalized_confirmed_covid_7_day_sum': 'sum', 'inpatient_beds_7_day_sum':'sum', 'total_icu_beds_7_day_sum':'sum', 
                                                                                                                       'total_staffed_adult_icu_beds_7_day_sum':'sum', 'icu_beds_used_7_day_sum':'sum', 'staffed_adult_icu_bed_occupancy_7_day_sum':'sum', 'staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum':'sum', 'staffed_icu_adult_patients_confirmed_covid_7_day_sum':'sum'}).reset_index()
hospital_data_df2

,fips_date,total_beds_7_day_sum,all_adult_hospital_beds_7_day_sum,all_adult_hospital_inpatient_beds_7_day_sum,inpatient_beds_used_7_day_sum,all_adult_hospital_inpatient_bed_occupied_7_day_sum,total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum,total_adult_patients_hospitalized_confirmed_covid_7_day_sum,inpatient_beds_7_day_sum,total_icu_beds_7_day_sum,total_staffed_adult_icu_beds_7_day_sum,icu_beds_used_7_day_sum,staffed_adult_icu_bed_occupancy_7_day_sum,staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum,staffed_icu_adult_patients_confirmed_covid_7_day_sum
0,10001.02020-07-31,2100.0,1939.0,1688.0,1713.0,1558.0,152.0,84.0,1876.0,322.0,203.0,266.0,189.0,28.0,28.0
1,10001.02020-08-07,2100.0,1939.0,1694.0,1672.0,1548.0,112.0,71.0,1876.0,322.0,203.0,273.0,188.0,22.0,22.0
2,10001.02020-08-14,2100.0,1939.0,1210.0,1141.0,1028.0,132.0,55.0,1340.0,198.0,134.0,183.0,128.0,29.0,29.0
3,10001.02020-08-21,2100.0,1939.0,1729.0,1650.0,1502.0,93.0,57.0,1908.0,285.0,193.0,245.0,171.0,23.0,23.0
4,10001.02020-08-28,2100.0,1939.0,1939.0,1730.0,1624.0,65.0,49.0,2100.0,315.0,203.0,251.0,182.0,19.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159931,nan2021-09-24,1218.0,1204.0,1008.0,526.0,447.0,0.0,0.0,1218.0,49.0,49.0,37.0,37.0,0.0,0.0
159932,nan2021-10-01,1218.0,1204.0,1008.0,523.0,441.0,0.0,0.0,1218.0,49.0,49.0,34.0,34.0,0.0,0.0
159933,nan2021-10-08,1218.0,1204.0,1008.0,524.0,443.0,0.0,0.0,1218.0,49.0,49.0,38.0,38.0,0.0,0.0
159934,nan2021-10-15,1218.0,1204.0,1008.0,540.0,462.0,0.0,0.0,1218.0,49.0,49.0,41.0,41.0,0.0,0.0
159935,nan2021-10-22,1228.0,1214.0,1018.0,589.0,491.0,0.0,0.0,1228.0,49.0,49.0,19.0,19.0,0.0,0.0

In [151]:
hospital_data_df2.nunique()

fips_date                                                                    159936
total_beds_7_day_sum                                                          14147
all_adult_hospital_beds_7_day_sum                                             13411
all_adult_hospital_inpatient_beds_7_day_sum                                   13005
inpatient_beds_used_7_day_sum                                                 13155
all_adult_hospital_inpatient_bed_occupied_7_day_sum                           12421
total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum      5329
total_adult_patients_hospitalized_confirmed_covid_7_day_sum                    4924
inpatient_beds_7_day_sum                                                      13704
total_icu_beds_7_day_sum                                                       5221
total_staffed_adult_icu_beds_7_day_sum                                         4226
icu_beds_used_7_day_sum                                                        5046
staffed_adult_icu_bed_occupancy_7_day_sum                                      4240
staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum             2744
staffed_icu_adult_patients_confirmed_covid_7_day_sum                           2546
dtype: int64

In [155]:
df = hospital_data_df2.loc[hospital_data_df2['fips_date'].str.contains("nan", case=False)]
df

,fips_date,total_beds_7_day_sum,all_adult_hospital_beds_7_day_sum,all_adult_hospital_inpatient_beds_7_day_sum,inpatient_beds_used_7_day_sum,all_adult_hospital_inpatient_bed_occupied_7_day_sum,total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum,total_adult_patients_hospitalized_confirmed_covid_7_day_sum,inpatient_beds_7_day_sum,total_icu_beds_7_day_sum,total_staffed_adult_icu_beds_7_day_sum,icu_beds_used_7_day_sum,staffed_adult_icu_bed_occupancy_7_day_sum,staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum,staffed_icu_adult_patients_confirmed_covid_7_day_sum
159871,nan2020-07-31,2907.0,1728.0,1528.0,-998747.0,-999431.0,-999989.0,-1999998.0,2576.0,246.0,62.0,-999950.0,-999999.0,-999999.0,-999999.0
159872,nan2020-08-07,2657.0,1695.0,1548.0,-1998824.0,-1999403.0,-1999998.0,-1999998.0,2388.0,210.0,60.0,57.0,5.0,0.0,0.0
159873,nan2020-08-14,2847.0,1790.0,1627.0,-998662.0,-999344.0,-999989.0,-1999998.0,2600.0,255.0,63.0,50.0,6.0,0.0,0.0
159874,nan2020-08-21,2892.0,1868.0,1644.0,-998506.0,-999291.0,-999965.0,-999965.0,2708.0,320.0,62.0,55.0,15.0,0.0,0.0
159875,nan2020-08-28,2832.0,1774.0,1557.0,-1998570.0,-1999330.0,-999932.0,67.0,2661.0,316.0,63.0,54.0,15.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159931,nan2021-09-24,1218.0,1204.0,1008.0,526.0,447.0,0.0,0.0,1218.0,49.0,49.0,37.0,37.0,0.0,0.0
159932,nan2021-10-01,1218.0,1204.0,1008.0,523.0,441.0,0.0,0.0,1218.0,49.0,49.0,34.0,34.0,0.0,0.0
159933,nan2021-10-08,1218.0,1204.0,1008.0,524.0,443.0,0.0,0.0,1218.0,49.0,49.0,38.0,38.0,0.0,0.0
159934,nan2021-10-15,1218.0,1204.0,1008.0,540.0,462.0,0.0,0.0,1218.0,49.0,49.0,41.0,41.0,0.0,0.0
159935,nan2021-10-22,1228.0,1214.0,1018.0,589.0,491.0,0.0,0.0,1228.0,49.0,49.0,19.0,19.0,0.0,0.0

In [156]:
hospital_data_df2['fips_date'].tail(70)

159866    9015.02021-09-24
159867    9015.02021-10-01
159868    9015.02021-10-08
159869    9015.02021-10-15
159870    9015.02021-10-22
                ...
159931       nan2021-09-24
159932       nan2021-10-01
159933       nan2021-10-08
159934       nan2021-10-15
159935       nan2021-10-22
Name: fips_date, Length: 70, dtype: object

In [167]:
f = hospital_data_df['fips'].unique()

In [168]:
x = nyt_data_grouped['fips'].unique()

In [178]:
y = list(set(x).symmetric_difference(set(f)))
y

[65536.0,
 nan,
 32771.0,
 '51085.0',
 98310.0,
 32778.0,
 65548.0,
 '48075.0',
 '46095.0',
 '5017.0',
 '40029.0',
 16407.0,
 65560.0,
 '49055.0',
 98331.0,
 98332.0,
 32796.0,
 '19001.0',
 '31035.0',
 32803.0,
 '18099.0',
 32806.0,
 '22033.0',
 32809.0,
 '8037.0',
 49201.0,
 '27091.0',
 98356.0,
 98362.0,
 32827.0,
 '50027.0',
 98368.0,
 98372.0,
 65605.0,
 49221.0,
 '27117.0',
 '51800.0',
 '24001.0',
 '48403.0',
 '28127.0',
 65613.0,
 65615.0,
 '17097.0',
 82001.0,
 '48067.0',
 '35055.0',
 65625.0,
 49242.0,
 98405.0,
 '17169.0',
 '12009.0',
 '45013.0',
 98415.0,
 '13299.0',
 '17039.0',
 '21053.0',
 16501.0,
 '27071.0',
 16509.0,
 '27087.0',
 32901.0,
 49286.0,
 '6029.0',
 '8121.0',
 '39133.0',
 32907.0,
 '48271.0',
 '54087.0',
 '28085.0',
 '48341.0',
 '48487.0',
 82072.0,
 49307.0,
 '27019.0',
 '12039.0',
 '18131.0',
 16544.0,
 '27065.0',
 32932.0,
 16550.0,
 32935.0,
 '37133.0',
 65708.0,
 32940.0,
 '31061.0',
 '41039.0',
 32955.0,
 '45075.0',
 '17081.0',
 32960.0,
 '39145.0',
 98499.0,
 '54097.0',
 98502.0,
 98506.0,
 '40065.0',
 32978.0,
 '5127.0',
 98520.0,
 16601.0,
 '20071.0',
 '27083.0',
 '29217.0',
 98531.0,
 '5111.0',
 '8075.0',
 '26135.0',
 98541.0,
 '46017.0',
 65775.0,
 '28033.0',
 '18165.0',
 33012.0,
 33013.0,
 '55113.0',
 33016.0,
 '18137.0',
 '37043.0',
 33021.0,
 33024.0,
 33028.0,
 33029.0,
 16646.0,
 49412.0,
 '48367.0',
 49417.0,
 33033.0,
 65804.0,
 16652.0,
 65807.0,
 33040.0,
 49423.0,
 '19111.0',
 49431.0,
 98584.0,
 82201.0,
 98586.0,
 33050.0,
 '41061.0',
 '42053.0',
 16673.0,
 49442.0,
 '54079.0',
 33063.0,
 33064.0,
 33065.0,
 33070.0,
 49455.0,
 16686.0,
 82225.0,
 '49009.0',
 '47093.0',
 '32033.0',
 49464.0,
 '55139.0',
 98620.0,
 '51021.0',
 82240.0,
 98624.0,
 98632.0,
 '55097.0',
 49503.0,
 16735.0,
 49506.0,
 '21039.0',
 '72111.0',
 33128.0,
 98668.0,
 '13199.0',
 33134.0,
 49519.0,
 33136.0,
 33137.0,
 98672.0,
 33140.0,
 '36105.0',
 33143.0,
 33146.0,
 '21191.0',
 82301.0,
 33150.0,
 98686.0,
 '28089.0',
 33155.0,
 '72005.0',
 '17037.0',
 '18147.0',
 '5085.0',
 33175.0,
 33176.0,
 '8093.0',
 '21035.0',
 33180.0,
 '48339.0',
 '49039.0',
 16803.0,
 '4009.0',
 '17015.0',
 33196.0,
 '32011.0',
 '41001.0',
 16830.0,
 49601.0,
 '48137.0',
 '5091.0',
 '49019.0',
 '29075.0',
 '35035.0',
 '49047.0',
 66002.0,
 '47169.0',
 '48269.0',
 '47001.0',
 '37115.0',
 82401.0,
 49635.0,
 '47109.0',
 '69110.0',
 82410.0,
 '45057.0',
 '19029.0',
 49646.0,
 82414.0,
 66032.0,
 98801.0,
 '55021.0',
 '40007.0',
 '48005.0',
 98807.0,
 '19053.0',
 '20093.0',
 98812.0,
 66044.0,
 49660.0,
 82431.0,
 98816.0,
 66048.0,
 '19093.0',
 82435.0,
 '18139.0',
 16901.0,
 '72043.0',
 98823.0,
 '72139.0',
 98826.0,
 82443.0,
 66061.0,
 49677.0,
 66067.0,
 49684.0,
 33301.0,
 98837.0,
 66071.0,
 16915.0,
 98841.0,
 33308.0,
 98848.0,
 '48421.0',
 '12037.0',
 '48441.0',
 33316.0,
 33317.0,
 '72095.0',
 98855.0,
 33321.0,
 49707.0,
 33324.0,
 '51015.0',
 66097.0,
 33331.0,
 16947.0,
 49720.0,
 '38051.0',
 '48479.0',
 '46061.0',
 '48273.0',
 66112.0,
 '29041.0',
 '26031.0',
 82501.0,
 '72063.0',
 49735.0,
 '49029.0',
 49738.0,
 '39043.0',
 '21225.0',
 '13247.0',
 '27153.0',
 98902.0,
 '18013.0',
 603.0,
 '31017.0',
 613.0,
 614.0,
 '19043.0',
 '51111.0',
 49770.0,
 '48335.0',
 '1037.0',
 98926.0,
 66160.0,
 17011.0,
 49781.0,
 631.0,
 17015.0,
 33401.0,
 49783.0,
 '24025.0',
 '20175.0',
 33407.0,
 98944.0,
 641.0,
 33410.0,
 '46102.0',
 98948.0,
 33414.0,
 49801.0,
 33418.0,
 17033.0,
 '49015.0',
 17042.0,
 '31183.0',
 17044.0,
 33428.0,
 33430.0,
 '53021.0',
 '21057.0',
 33435.0,
 66204.0,
 '72037.0',
 '26087.0',
 33440.0,
 66209.0,
 674.0,
 66211.0,
 66212.0,
 66213.0,
 49829.0,
 66215.0,
 680.0,
 681.0,
 676.0,
 683.0,
 82601.0,
 682.0,
 66219.0,
 '27089.0',
 82609.0,
 33458.0,
 '53039.0',
 693.0,
 33462.0,
 33461.0,
 '36107.0',
 49849.0,
 698.0,
 '38087.0',
 '5079.0',
 '28097.0',
 49854.0,
 33470.0,
 49855.0,
 705.0,
 '29125.0',
 49862.0,
 '48091.0',
 82633.0,
 33484.0,
 17101.0,
 33486.0,
 49868.0,
 717.0,
 17105.0,
 725.0,
 '51840.0',
 733.0,
 '55081.0',
 737.0,
 738.0,
 33511.0,
 '20139.0',
 '13077.0',
 '21021.0',
 33525.0,
 '47157.0',
 '48247.0',
 49913.0,
 '29005.0',
 '40129.0',
 765.0,
 '28133.0',
 33541.0,
 '29091.0',
 775.0,
 33544.0,
 49930.0,
 780.0,
 82701.0,
 49935.0,
 785.0,
 49938.0,
 791.0,
 792.0,
 '48499.0',
 49946.0,
 33563.0,
 82716.0,
 '53051.0',
 801.0,
 49953.0,
 '41005.0',
 99109.0,
 33573.0,
 99111.0,
 '17067.0',
 82729.0,
 99114.0,
 17201.0,
 99122.0,
 '33001.0',
 820.0,
 '42051.0',
 '26075.0',
 '51071.0',
 99133.0,
 '27031.0',
 '27171.0',
 33603.0,
 33606.0,
 33609.0,
 '20145.0',
 33611.0,
 33612.0,
 33613.0,
 33614.0,
 '29013.0',
 17233.0,
 99156.0,
 '48201.0',
 99159.0,
 50010.0,
 99163.0,
 99166.0,
 '20045.0',
 99169.0,
 50022.0,
 '36059.0',
 50025.0,
 '26067.0',
 '47107.0',
 82801.0,
 50036.0,
 17268.0,
 50049.0,
 66434.0,
 '20131.0',
 66436.0,
 99204.0,
 '31095.0',
 '48229.0',
 99208.0,
 66441.0,
 99210.0,
 907.0,
 50060.0,
 909.0,
 910.0,
 33677.0,
 99216.0,
 912.0,
 82834.0,
 915.0,
 '6045.0',
 '31119.0',
 918.0,
 919.0,
 '37031.0',
 '29189.0',
 '9005.0',
 923.0,
 '13107.0',
 927.0,
 928.0,
 '18081.0',
 33701.0,
 935.0,
 936.0,
 33705.0,
 '12105.0',
 33707.0,
 33709.0,
 17325.0,
 33710.0,
 '13065.0',
 '21127.0',
 17331.0,
 '45091.0',
 956.0,
 '46057.0',
 959.0,
 960.0,
 961.0,
 50112.0,
 50115.0,
 '18007.0',
 '13165.0',
 66502.0,
 '27097.0',
 '15009.0',
 969.0,
 '28065.0',
 '31185.0',
 66508.0,
 50126.0,
 50129.0,
 979.0,
 '28059.0',
 82901.0,
 984.0,
 66521.0,
 50138.0,
 '20117.0',
 33756.0,
 '51057.0',
 '47051.0',
 50144.0,
 '28045.0',
 99301.0,
 66534.0,
 '17129.0',
 '51590.0',
 '28053.0',
 33770.0,
 66538.0,
 '19187.0',
 '72097.0',
 50158.0,
 '48317.0',
 '13317.0',
 82930.0,
 66547.0,
 '48333.0',
 '39071.0',
 17402.0,
 17403.0,
 99328.0,
 17408.0,
 99336.0,
 '39101.0',
 '39017.0',
 33805.0,
 '29053.0',
 '29095.0',
 1040.0,
 99344.0,
 99347.0,
 99350.0,
 99352.0,
 50201.0,
 '47105.0',
 '20007.0',
 '38103.0',
 '28163.0',
 50208.0,
 '6075.0',
 99362.0,
 1060.0,
 50213.0,
 '48457.0',
 33831.0,
 '41041.0',
 '30059.0',
 50219.0,
 50220.0,
 66604.0,
 1069.0,
 33837.0,
 66606.0,
 '42119.0',
 '20195.0',
 '55029.0',
 '8043.0',
 '21135.0',
 83001.0,
 33853.0,
 1085.0,
 99403.0,
 33870.0,
 1104.0,
 33873.0,
 33872.0,
 '51037.0',
 '18035.0',
 33881.0,
 '27053.0',
 '78030.0',
 50273.0,
 '13121.0',
 '55079.0',
 '17007.0',
 '6043.0',
 '20039.0',
 33901.0,
 '31145.0',
 33905.0,
 17522.0,
 '45061.0',
 33912.0,
 50309.0,
 17543.0,
 '21033.0',
 '46049.0',
 50314.0,
 '29037.0',
 33936.0,
 '48167.0',
 83101.0,
 33950.0,
 '16039.0',
 33952.0,
 66720.0,
 '47175.0',
 66725.0,
 83110.0,
 '8125.0',
 '17151.0',
 99503.0,
 66736.0,
 1201.0,
 99506.0,
 66739.0,
 99508.0,
 1199.0,
 '28105.0',
 66743.0,
 '37011.0',
 '39013.0',
 66749.0,
 '51081.0',
 17602.0,
 66757.0,
 33990.0,
 66762.0,
 '31143.0',
 1230.0,
 '17099.0',
 '46129.0',
 '40145.0',
 50401.0,
 '51041.0',
 '48015.0',
 66801.0,
 '30093.0',
 '37019.0',
 50421.0,
 99574.0,
 50423.0,
 '6067.0',
 83201.0,
 '51045.0',
 50441.0,
 83211.0,
 '29186.0',
 83213.0,
 99603.0,
 1301.0,
 83221.0,
 66839.0,
 '48455.0',
 '21075.0',
 '18133.0',
 50461.0,
 66846.0,
 99615.0,
 '37171.0',
 17701.0,
 '17049.0',
 '47009.0',
 '20015.0',
 66861.0,
 '51115.0',
 1331.0,
 83252.0,
 34102.0,
 83254.0,
 34108.0,
 99645.0,
 '48281.0',
 83263.0,
 '51093.0',
 '18093.0',
 50501.0,
 34119.0,
 '51139.0',
 83276.0,
 17740.0,
 50511.0,
 99664.0,
 17745.0,
 '51095.0',
 '1091.0',
 '51017.0',
 66901.0,
 99669.0,
 '39159.0',
 '12079.0',
 17756.0,
 50525.0,
 '13063.0',
 '54001.0',
 17764.0,
 83301.0,
 99686.0,
 '30043.0',
 50536.0,
 '19129.0',
 '56011.0',
 '18145.0',
 '20033.0',
 50548.0,
 99701.0,
 83318.0,
 66935.0,
 99703.0,
 '20025.0',
 '44005.0',
 '20051.0',
 66945.0,
 83330.0,
 '48327.0',
 83338.0,
 83340.0,
 66956.0,
 50574.0,
 '13213.0',
 '20187.0',
 '17109.0',
 '6025.0',
 83350.0,
 66967.0,
 50583.0,
 1432.0,
 34202.0,
 17815.0,
 50588.0,
 66968.0,
 17822.0,
 '13207.0',
 34208.0,
 34209.0,
 1440.0,
 50595.0,
 '19017.0',
 '40105.0',
 17837.0,
 1453.0,
 34223.0,
 '48151.0',
 '51001.0',
 '51595.0',
 50613.0,
 '42043.0',
 50616.0,
 34233.0,
 67002.0,
 67003.0,
 67005.0,
 34239.0,
 34240.0,
 83404.0,
 50638.0,
 67022.0,
 '72057.0',
 50644.0,
 67029.0,
 '39089.0',
 34265.0,
 99801.0,
 '12053.0',
 '48413.0',
 67037.0,
 83422.0,
 67042.0,
 50659.0,
 67045.0,
 50662.0,
 '47095.0',
 '17155.0',
 17901.0,
 67054.0,
 34285.0,
 83440.0,
 50674.0,
 '29001.0',
 50677.0,
 67063.0,
 99833.0,
 67068.0,
 67070.0,
 '13277.0',
 1542.0,
 83467.0,
 '20161.0',
 1550.0,
 50702.0,
 50703.0,
 '19037.0',
 '20057.0',
 '20083.0',
 '21209.0',
 67104.0,
 67107.0,
 '56037.0',
 '8011.0',
 '40133.0',
 17961.0,
 67114.0,
 83501.0,
 1581.0,
 '21133.0',
 '31111.0',
 67124.0,
 '18083.0',
 '48111.0',
 '29019.0',
 '17141.0',
 99901.0,
 '18011.0',
 83522.0,
 '36077.0',
 1605.0,
 '21101.0',
 1608.0,
 '36021.0',
 83530.0,
 '48431.0',
 67156.0,
 83544.0,
 '12019.0',
 18015.0,
 18017.0,
 '72093.0',
 '40041.0',
 50801.0,
 '1023.0',
 '20031.0',
 1655.0,
 18042.0,
 '42133.0',
 34428.0,
 18045.0,
 '21161.0',
 '36015.0',
 67214.0,
 '48053.0',
 '53047.0',
 67220.0,
 83605.0,
 34452.0,
 50841.0,
 67226.0,
 83611.0,
 50849.0,
 83617.0,
 67235.0,
 '2261.0',
 1701.0,
 50854.0,
 '48177.0',
 '51660.0',
 '36019.0',
 34474.0,
 '21193.0',
 '45059.0',
 34484.0,
 '6063.0',
 18102.0,
 83638.0,
 18104.0,
 18103.0,
 '47117.0',
 '48155.0',
 '5147.0',
 '4023.0',
 83647.0,
 '34021.0',
 '13081.0',
 '27127.0',
 '23025.0',
 '40055.0',
 '13295.0',
 '5143.0',
 '19087.0',
 1742.0,
 '31091.0',
 1752.0,
 83672.0,
 '53055.0',
 1757.0,
 '53003.0',
 '30037.0',
 83687.0,
 '12081.0',
 '26007.0',
 '21017.0',
 83704.0,
 83706.0,
 '49049.0',
 83709.0,
 83712.0,
 '21117.0',
 67337.0,
 1803.0,
 '41021.0',
 '54105.0',
 '47151.0',
 '21151.0',
 '39059.0',
 '21013.0',
 18201.0,
 67357.0,
 '51630.0',
 '29021.0',
 '27047.0',
 67361.0,
 34601.0,
 18218.0,
 1835.0,
 '13069.0',
 1842.0,
 1844.0,
 34613.0,
 '37147.0',
 18235.0,
 '19095.0',
 1854.0,
 '41009.0',
 51012.0,
 67401.0,
 34637.0,
 51023.0,
 '8077.0',
 67410.0,
 '22049.0',
 1876.0,
 51031.0,
 '36003.0',
 67420.0,
 83805.0,
 34652.0,
 34655.0,
 51040.0,
 51041.0,
 1890.0,
 83814.0,
 '41011.0',
 67432.0,
 34667.0,
 '34009.0',
 67439.0,
 '31055.0',
 '19069.0',
 '19113.0',
 '46031.0',
 67449.0,
 '20137.0',
 1915.0,
 '37029.0',
 83837.0,
 18301.0,
 67455.0,
 67456.0,
 34689.0,
 '12115.0',
 83843.0,
 67460.0,
 '21153.0',
 '39067.0',
 34695.0,
 '5053.0',
 34698.0,
 67467.0,
 83854.0,
 '1107.0',
 67473.0,
 83861.0,
 34711.0,
 83864.0,
 '55095.0',
 51101.0,
 1950.0,
 '55023.0',
 51104.0,
 67502.0,
 1970.0,
 34741.0,
 '26159.0',
 18360.0,
 '17143.0',
 34748.0,
 ...]

In [180]:
# for x in y:
#     if 

# hospital_data_df3 = hospital_data_df2.drop(hospital_data_df2['fips_date'] == y)
# hospital_data_df3

In [181]:
merged = hospital_data_df2.merge(nyt_data_grouped)

In [183]:
clean_merge = merged.dropna()

,fips_date,total_beds_7_day_sum,all_adult_hospital_beds_7_day_sum,all_adult_hospital_inpatient_beds_7_day_sum,inpatient_beds_used_7_day_sum,all_adult_hospital_inpatient_bed_occupied_7_day_sum,total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum,total_adult_patients_hospitalized_confirmed_covid_7_day_sum,inpatient_beds_7_day_sum,total_icu_beds_7_day_sum,total_staffed_adult_icu_beds_7_day_sum,icu_beds_used_7_day_sum,staffed_adult_icu_bed_occupancy_7_day_sum,staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum,staffed_icu_adult_patients_confirmed_covid_7_day_sum,fips,date,cases,deaths
0,10001.02020-07-31,2100.0,1939.0,1688.0,1713.0,1558.0,152.0,84.0,1876.0,322.0,203.0,266.0,189.0,28.0,28.0,10001.0,2020-07-31,14925,737.0
1,10001.02020-08-07,2100.0,1939.0,1694.0,1672.0,1548.0,112.0,71.0,1876.0,322.0,203.0,273.0,188.0,22.0,22.0,10001.0,2020-08-07,15576,749.0
2,10001.02020-08-14,2100.0,1939.0,1210.0,1141.0,1028.0,132.0,55.0,1340.0,198.0,134.0,183.0,128.0,29.0,29.0,10001.0,2020-08-14,16348,756.0
3,10001.02020-08-21,2100.0,1939.0,1729.0,1650.0,1502.0,93.0,57.0,1908.0,285.0,193.0,245.0,171.0,23.0,23.0,10001.0,2020-08-21,17518,759.0
4,10001.02020-08-28,2100.0,1939.0,1939.0,1730.0,1624.0,65.0,49.0,2100.0,315.0,203.0,251.0,182.0,19.0,19.0,10001.0,2020-08-28,17907,763.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159059,9015.02021-09-24,951.0,937.0,783.0,565.0,565.0,56.0,42.0,783.0,119.0,119.0,34.0,34.0,14.0,10.0,9015.0,2021-09-24,85476,1400.0
159060,9015.02021-10-01,956.0,942.0,788.0,530.0,530.0,61.0,57.0,788.0,119.0,119.0,32.0,32.0,15.0,14.0,9015.0,2021-10-01,87031,1439.0
159061,9015.02021-10-08,956.0,942.0,788.0,557.0,557.0,87.0,85.0,788.0,119.0,119.0,32.0,32.0,20.0,20.0,9015.0,2021-10-08,88585,1474.0
159062,9015.02021-10-15,955.0,941.0,787.0,521.0,521.0,76.0,74.0,787.0,119.0,119.0,26.0,26.0,19.0,19.0,9015.0,2021-10-15,90074,1483.0
159063,9015.02021-10-22,952.0,938.0,784.0,550.0,550.0,84.0,75.0,784.0,119.0,119.0,32.0,32.0,29.0,28.0,9015.0,2021-10-22,91747,1499.0